export const categories = ["Yellow", "Red", "White", "Blue"];
export const statuses = ["Requested", "Assigned", "Collector En Route", "Picked Up", "In Transit", "Delivered", "Processed"];

export const requestSeed = [
  [
    "REQ-24091",
    "Apollo Hospitals",
    "Yellow",
    "12.4 kg",
    "High",
    "Arjun Mehta",
    "Today, 10:30 AM",
    "Collector En Route",
  ],
  [
    "REQ-24090",
    "Fortis Bannerghatta",
    "Red",
    "8.2 kg",
    "Normal",
    "Priya Nair",
    "Today, 11:15 AM",
    "Assigned",
  ],
  [
    "REQ-24089",
    "Manipal Whitefield",
    "White",
    "5.8 kg",
    "Normal",
    "Unassigned",
    "Tomorrow, 09:00 AM",
    "Requested",
  ],
  [
    "REQ-24088",
    "Narayana Health",
    "Blue",
    "3.1 kg",
    "Normal",
    "Arjun Mehta",
    "Today, 08:45 AM",
    "Picked Up",
  ],
  [
    "REQ-24087",
    "Cloudnine Hospital",
    "Yellow",
    "18.6 kg",
    "Emergency",
    "Kavya Singh",
    "Today, 07:30 AM",
    "In Transit",
  ],
  [
    "REQ-24086",
    "Sakra World Hospital",
    "Red",
    "9.4 kg",
    "High",
    "Vikram Shah",
    "Yesterday, 04:20 PM",
    "Delivered",
  ],
  [
    "REQ-24085",
    "Aster CMI Hospital",
    "White",
    "6.7 kg",
    "Normal",
    "Priya Nair",
    "Yesterday, 01:00 PM",
    "Processed",
  ],
  [
    "REQ-24084",
    "Columbia Asia Hebbal",
    "Yellow",
    "14.1 kg",
    "Normal",
    "Arjun Mehta",
    "Yesterday, 11:10 AM",
    "Processed",
  ],
  [
    "REQ-24083",
    "St. Martha's Hospital",
    "Blue",
    "4.2 kg",
    "High",
    "Unassigned",
    "Tomorrow, 10:00 AM",
    "Requested",
  ],
  [
    "REQ-24082",
    "BGS Gleneagles",
    "Red",
    "11.8 kg",
    "Normal",
    "Kavya Singh",
    "Today, 02:30 PM",
    "Assigned",
  ],
  [
    "REQ-24081",
    "HOSMAT Hospital",
    "Yellow",
    "7.5 kg",
    "Normal",
    "Vikram Shah",
    "Today, 03:00 PM",
    "Collector En Route",
  ],
  [
    "REQ-24080",
    "Bangalore Baptist",
    "White",
    "2.8 kg",
    "Normal",
    "Priya Nair",
    "Mon, 09:30 AM",
    "Processed",
  ],
  [
    "REQ-24079",
    "Rajarajeshwari Medical",
    "Blue",
    "5.4 kg",
    "High",
    "Arjun Mehta",
    "Mon, 12:00 PM",
    "In Transit",
  ],
  [
    "REQ-24078",
    "Vikram Hospital",
    "Yellow",
    "16.2 kg",
    "Emergency",
    "Kavya Singh",
    "Mon, 08:10 AM",
    "Picked Up",
  ],
  [
    "REQ-24077",
    "People Tree Hospital",
    "Red",
    "6.3 kg",
    "Normal",
    "Unassigned",
    "Tue, 10:00 AM",
    "Requested",
  ],
].map(
  ([
    id,
    facility,
    category,
    quantity,
    priority,
    collector,
    pickup,
    status,
  ]) => ({
    id,
    facility,
    category,
    quantity,
    priority,
    collector,
    pickup,
    status,
  }),
);

export const wasteTrend = [
  { day: "Mon", value: 31 },
  { day: "Tue", value: 42 },
  { day: "Wed", value: 35 },
  { day: "Thu", value: 48 },
  { day: "Fri", value: 45 },
  { day: "Sat", value: 52 },
  { day: "Sun", value: 46 },
];

export const categoryData = [
  { name: "Yellow", value: 42, color: "#e7b94a" },
  { name: "Red", value: 26, color: "#e5766c" },
  { name: "Blue", value: 18, color: "#6aa8d7" },
  { name: "White", value: 14, color: "#b6c4d5" },
];

export type Request = (typeof requestSeed)[number];
